import React, { createContext, useContext, useState } from 'react';

const t = {
  uz: {
    nav_home: 'Bosh sahifa', nav_about: 'Biz haqimizda', nav_courses: 'Kurslar',
    nav_branches: 'Filiallar', nav_reviews: 'Sharhlar', nav_enroll: "Ro'yxat",
    hero_label: "Toshkentning №1 ta'lim markazi",
    hero_title_1: 'Kelajagingizni', hero_title_2: 'Biz Bilan', hero_title_3: 'Shakllantiring',
    hero_sub: "IBRAT Talim — yosh tadbirkor Shahriyor Hamrayev tomonidan tashkil etilgan zamonaviy ta'lim markazi. Xorijiy tillar va bolalar erta rivojlanishi yo'nalishida ilg'or ta'lim berish bizning maqsadimiz.",
    btn_explore: 'Kurslarni Ko\'rish', btn_join: 'Hoziroq Qo\'shiling',
    widget_enroll: '⚡ Tez ro\'yxatdan o\'ting',
    about_label: 'Bizning Hikoyamiz', about_title: 'Missiya va Qadriyatlar',
    about_p: "IBRAT Talim bir sinf xonasidan boshlanib, Toshkent bo'ylab keng tarmoqli ta'lim markaziga aylandi. Bizning shijoratimiz: <strong>yoshlar tomonidan, yoshlar uchun</strong> yaratilgan sifatli ta'lim.",
    feat_1_title: 'Zamonaviy Metodlar', feat_1_p: "Montessori, interfaol o'qitish va ilg'or pedagogik texnologiyalar orqali tez va samarali natijaga erishamiz.",
    feat_2_title: "Tajribali O'qituvchilar", feat_2_p: "Har bir o'qituvchi o'z sohasining mutaxassisi bo'lib, o'quvchiga individual yondashuv asosida dars o'tadi.",
    feat_3_title: 'Barcha Yoshlar Uchun', feat_3_p: "2 yoshli bolalardan tortib kattalar o'quvchilargacha — har bir yosh guruh uchun maxsus dasturlar mavjud.",
    adv_1_title: 'Yuqori Sifat', adv_1_p: "Xalqaro standartlarga mos darsliklar va tizim.",
    adv_2_title: 'Innovatsiya', adv_2_p: "Interaktiv 3D platformalar va amaliy loyihalar.",
    adv_3_title: 'Kafolat', adv_3_p: "Siz kutgan natija va mustahkam bilim asosi.",
    stat_students: "Mamnun o'quvchilar", stat_teachers: "Tajribali o'qituvchilar", stat_programs: 'Kurs dasturlari', stat_years: 'Yillik tajriba',
    proc_label: 'Qanday Ishlashimiz', proc_title: '4 ta oddiy', proc_title_green: 'Qadam',
    proc_1: 'Konsultatsiya', proc_1_p: 'Maqsadlaringizni aniqlaymiz va siz uchun eng mos kursni tavsiya qilamiz.',
    proc_2: 'Daraja Testi', proc_2_p: 'Bepul diagnostik test orqali sizga mos guruhni aniqlaymiz.',
    proc_3: "Faol O'qish", proc_3_p: "Zamonaviy sinf xonalarda tajribali o'qituvchilar bilan interaktiv darslar.",
    proc_4: 'Natijaga Erishing', proc_4_p: "Imtihonlardan o'ting, sertifikat oling (IELTS va boshqalar) va yangi bilimingizni qo'llang!",
    courses_label: "Ta'lim Yo'nalishlari", courses_title: 'Bizning', courses_title_green: 'Kurslar',
    tab_all: 'Barchasi', tab_lang: 'Xorijiy Tillar', tab_kids: 'Bolalar', tab_exam: 'Imtihon Tayyorgarligi',
    c_en_name: 'Ingliz Tili', c_en_desc: "Boshlang'ichdan ilg'orgacha. IELTS tayyorgarligi, speaking club.",
    c_ru_name: 'Rus Tili', c_ru_desc: 'Jonli muloqotga yo\'naltirilgan intensiv kurs. Grammatika va suhbat.',
    c_ar_name: 'Arab Tili', c_ar_desc: "Grammatika, o'qish va zamonaviy suhbat. Quron arabchasi ham o'rgatiladi.",
    c_ko_name: 'Koreys Tili', c_ko_desc: 'Hangul alifbodan K-pop va biznes koreyscha suhbatga qadar.',
    c_ma_name: 'Mental Arifmetika', c_ma_desc: 'Abakus orqali tez hisoblab, mantiqiy tafakkurni rivojlantirish. 5–14 yosh.',
    c_mt_name: 'Montessori', c_mt_desc: "Bolaning mustaqil o'rganish qobiliyatini uyg'otuvchi ilg'or metodika. 2–7 yosh.",
    c_ielts_name: 'IELTS / DTM Tayyorlik', c_ielts_desc: 'Band 7+ maqsadiga yo\'naltirilgan intensiv tayyorlov. Mock testlar kiritilgan.',
    c_sr_name: "Tez O'qish", c_sr_desc: "O'qish tezligini 3–5 barobar oshirish va ma'lumotni yaxshiroq esda saqlash texnikasi.",
    learn_more: 'Batafsil',
    branches_label: 'Bizning Filiallar', branches_title: 'Toshkentdagi', branches_title_green: 'Manzillarimiz',
    branches_sub: 'Sizga yaqin filialni toping. Biz doimo kengaymoqdamiz.',
    br_1_name: 'Oltintepa Filiali', br_1_addr: "Ko'ksaroy, Shifobaxsh suvlar ko'chasi, 134", br_1_lm: '"Oltintepa" masjidi yaqinida',
    br_2_name: 'Yangi Darhon Filiali', br_2_addr: "Navro'z ko'chasi, 20", br_2_lm: 'Yangi Darhon mahallasi',
    br_3_name: 'Yangihayot Filiali', br_3_addr: "Yo'ldosh-16, 12, Yangihayot tumani", br_3_lm: '37-poliklinika yaqinida',
    label_location: 'Manzil', label_landmark: "Mo'ljal", label_hours: 'Ish vaqti', label_phone: 'Telefon',
    btn_map: 'Xaritada Ko\'rish',
    gallery_label: 'Foto Galereya', gallery_title: 'IBRAT Talim', gallery_title_green: 'Ichidan',
    g1: 'Zamonaviy Sinflar', g2: "Interfaol O'qish", g3: 'Guruh Muhokamasi',
    g4: 'Bolalar Rivojlanishi', g5: "O'quvchi Muvaffaqiyati", g6: 'Mutaxassis Maslahati',
    reviews_label: "O'quvchilar Fikri", reviews_title: 'Muvaffaqiyat', reviews_title_green: 'Hikoyalari',
    t1_text: '"Qizim Montessori darslarini juda yaxshi ko\'radi! Uning o\'ziga bo\'lgan ishonchi oshdi, o\'qituvchilar esa juda mehribon va malakali."',
    t1_role: '5 yoshli farzand onasi',
    t2_text: '"Intensiv rus tili kursi orqali orzuimdagi ishni topdim. Bu yerning metodikasi amaliy va natijaga yo\'naltirilgan."',
    t2_role: "Katta o'quvchi",
    t3_text: '"Mental arifmetika o\'g\'limning fikrlash tarzini o\'zgartirdi. U endi murakkab masalalarni mendan tezroq yechadi!"',
    t3_role: '9 yoshli farzand onasi',
    contact_label: 'Aloqa', contact_title: 'Sayohatingizni Boshlang',
    contact_sub: "Ro'yxatdan o'tishga tayor yoki savolingiz bormi? Formani to'ldiring — jamoamiz tez orada siz bilan bog'lanadi.",
    form_name: "To'liq Ism", form_name_ph: 'Ismingiz Familiyangiz',
    form_phone: 'Telefon Raqami', form_course: 'Kurs', form_course_ph: 'Kursni tanlang',
    form_msg: 'Xabar (ixtiyoriy)', form_msg_ph: 'Savolingiz yoki izohingiz...',
    btn_send: "So'rov Yuborish",
    footer_desc: "Innovatsion ta'lim orqali aqllarni kuchaytirish. Jamoamizga qo'shiling va kelajagingizni bugun shakllantiring.",
    footer_links: 'Tezkor Havolalar', footer_branches: 'Filiallarimiz',
    footer_contact: "Bog'laning", footer_info: "Qo'shimcha ma'lumot uchun:",
    footer_copy: '© 2026 IBRAT Talim. Barcha huquqlar himoyalangan.',
    cta_float: 'Hoziroq Yozil',
    course_back: 'Orqaga', about_course: 'Kurs Haqida', what_learn: 'Nima O\'rganasiz',
    course_info: 'Kurs Ma\'lumotlari', label_duration: 'Davomiyligi',
    label_level: 'Daraja', label_cert: 'Sertifikat', val_yes: 'Ha',
    btn_enroll: 'Ro\'yxatdan O\'tish', more_courses: 'Boshqa', more_courses_green: 'Kurslar',
    form_name_w: 'Ismingiz', form_course_w: 'Kursni tanlang',
  },
  ru: {
    nav_home: 'Главная', nav_about: 'О нас', nav_courses: 'Курсы',
    nav_branches: 'Филиалы', nav_reviews: 'Отзывы', nav_enroll: 'Запись',
    hero_label: 'Образовательный центр №1 в Ташкенте',
    hero_title_1: 'Формируйте', hero_title_2: 'Своё Будущее', hero_title_3: 'Вместе с Нами',
    hero_sub: 'IBRAT Talim — современный образовательный центр, основанный молодым предпринимателем Шахриёром Хамраевым. Наша миссия: качественное образование, созданное молодыми для молодых.',
    btn_explore: 'Смотреть Курсы', btn_join: 'Записаться Сейчас',
    widget_enroll: '⚡ Быстрая запись',
    about_label: 'Наша История', about_title: 'Миссия и Ценности',
    about_p: 'IBRAT Talim начался с одного класса и вырос в разветвлённую сеть образовательных центров по Ташкенту. Наш девиз: качественное образование, созданное <strong>молодёжью для молодёжи</strong>.',
    feat_1_title: 'Современные Методы', feat_1_p: 'Методика Монтессори, интерактивное обучение и передовые педагогические технологии для быстрого и эффективного результата.',
    feat_2_title: 'Опытные Преподаватели', feat_2_p: 'Каждый преподаватель — эксперт в своей области, применяющий индивидуальный подход к каждому ученику.',
    feat_3_title: 'Для Всех Возрастов', feat_3_p: 'От малышей от 2 лет до взрослых учеников — специальные программы для каждой возрастной группы.',
    adv_1_title: 'Высокое Качество', adv_1_p: 'Учебные программы и система, соответствующие международным стандартам.',
    adv_2_title: 'Инновации', adv_2_p: 'Интерактивные 3D-платформы и практические проекты.',
    adv_3_title: 'Гарантия', adv_3_p: 'Ожидаемый вами результат и прочный фундамент знаний.',
    stat_students: 'Довольных учеников', stat_teachers: 'Опытных преподавателей', stat_programs: 'Учебных программ', stat_years: 'Лет опыта',
    proc_label: 'Как Мы Работаем', proc_title: '4 простых', proc_title_green: 'Шага',
    proc_1: 'Консультация', proc_1_p: 'Определяем ваши цели и рекомендуем наиболее подходящий курс.',
    proc_2: 'Тест Уровня', proc_2_p: 'Бесплатный диагностический тест для определения подходящей группы.',
    proc_3: 'Активное Обучение', proc_3_p: 'Интерактивные занятия в современных классах с опытными преподавателями.',
    proc_4: 'Достигните Результата', proc_4_p: 'Сдайте экзамены, получите сертификат (IELTS и др.) и применяйте новые знания!',
    courses_label: 'Направления Обучения', courses_title: 'Наши', courses_title_green: 'Курсы',
    tab_all: 'Все', tab_lang: 'Иностранные Языки', tab_kids: 'Для Детей', tab_exam: 'Подготовка к Экзаменам',
    c_en_name: 'Английский Язык', c_en_desc: 'От начального до продвинутого уровня. Подготовка к IELTS, speaking club.',
    c_ru_name: 'Русский Язык', c_ru_desc: 'Интенсивный курс с акцентом на живое общение. Грамматика и разговорная речь.',
    c_ar_name: 'Арабский Язык', c_ar_desc: 'Грамматика, чтение и современная разговорная речь. Коранический арабский.',
    c_ko_name: 'Корейский Язык', c_ko_desc: 'От алфавита Хангыль до разговорного корейского для K-pop и бизнеса.',
    c_ma_name: 'Ментальная Арифметика', c_ma_desc: 'Быстрый счёт на абакусе, развитие логического мышления. 5–14 лет.',
    c_mt_name: 'Монтессори', c_mt_desc: 'Прогрессивная методика для пробуждения самостоятельного обучения. 2–7 лет.',
    c_ielts_name: 'Подготовка IELTS / ДТМ', c_ielts_desc: 'Интенсивная подготовка для получения Band 7+. Включены пробные тесты.',
    c_sr_name: 'Скорочтение', c_sr_desc: 'Увеличение скорости чтения в 3–5 раз и улучшение запоминания информации.',
    learn_more: 'Подробнее',
    branches_label: 'Наши Филиалы', branches_title: 'Наши', branches_title_green: 'Адреса в Ташкенте',
    branches_sub: 'Найдите ближайший филиал. Мы постоянно расширяемся.',
    br_1_name: 'Филиал Олтинтепа', br_1_addr: 'Кукcарой, ул. Шифобахш сувлар, 134', br_1_lm: 'Рядом с мечетью "Олтинтепа"',
    br_2_name: 'Филиал Янги Дарҳон', br_2_addr: 'ул. Навруз, 20', br_2_lm: 'Махалля Янги Дарҳон',
    br_3_name: 'Филиал Янгихаёт', br_3_addr: 'Йулдош-16, 12, район Янгихаёт', br_3_lm: 'Рядом с 37-й поликлиникой',
    label_location: 'Адрес', label_landmark: 'Ориентир', label_hours: 'Часы работы', label_phone: 'Телефон',
    btn_map: 'Смотреть на Карте',
    gallery_label: 'Фотогалерея', gallery_title: 'IBRAT Talim', gallery_title_green: 'Изнутри',
    g1: 'Современные Классы', g2: 'Интерактивное Обучение', g3: 'Групповые Обсуждения',
    g4: 'Развитие Детей', g5: 'Успехи Учеников', g6: 'Экспертное Руководство',
    reviews_label: 'Отзывы Учеников', reviews_title: 'Истории', reviews_title_green: 'Успеха',
    t1_text: '"Моя дочь обожает занятия по Монтессори! Её уверенность в себе выросла, а учителя очень добрые и квалифицированные."',
    t1_role: 'Мама 5-летней дочери',
    t2_text: '"Интенсивный курс русского языка помог мне получить работу мечты. Методика здесь практичная и ориентированная на результат."',
    t2_role: 'Взрослый студент',
    t3_text: '"Ментальная арифметика изменила способ мышления моего сына. Теперь он решает сложные задачи быстрее меня!"',
    t3_role: 'Мама 9-летнего сына',
    contact_label: 'Связь', contact_title: 'Начните Свой Путь',
    contact_sub: 'Готовы записаться или есть вопросы? Заполните форму — наша команда свяжется с вами в ближайшее время.',
    form_name: 'Полное Имя', form_name_ph: 'Ваше имя и фамилия',
    form_phone: 'Номер Телефона', form_course: 'Курс', form_course_ph: 'Выберите курс',
    form_msg: 'Сообщение (необязательно)', form_msg_ph: 'Ваш вопрос или комментарий...',
    btn_send: 'Отправить Заявку',
    footer_desc: 'Развиваем умы через инновационное образование. Присоединяйтесь к нашему сообществу и формируйте своё будущее.',
    footer_links: 'Быстрые Ссылки', footer_branches: 'Наши Филиалы',
    footer_contact: 'Свяжитесь', footer_info: 'Для получения дополнительной информации:',
    footer_copy: '© 2026 IBRAT Talim. Все права защищены.',
    cta_float: 'Записаться Сейчас',
    course_back: 'Назад', about_course: 'О Курсе', what_learn: 'Что Вы Узнаете',
    course_info: 'Информация о Курсе', label_duration: 'Продолжительность',
    label_level: 'Уровень', label_cert: 'Сертификат', val_yes: 'Да',
    btn_enroll: 'Записаться', more_courses: 'Другие', more_courses_green: 'Курсы',
    form_name_w: 'Ваше имя', form_course_w: 'Выберите курс',
  },
  en: {
    nav_home: 'Home', nav_about: 'About', nav_courses: 'Courses',
    nav_branches: 'Branches', nav_reviews: 'Reviews', nav_enroll: 'Enroll',
    hero_label: 'Tashkent\'s #1 Educational Centre',
    hero_title_1: 'Shape Your', hero_title_2: 'Future', hero_title_3: 'With Us',
    hero_sub: 'IBRAT Talim is a modern educational centre founded by young entrepreneur Shahriyor Hamrayev. We provide world-class foreign language and early childhood development education.',
    btn_explore: 'Explore Courses', btn_join: 'Join Now',
    widget_enroll: '⚡ Quick Enroll',
    about_label: 'Our Story', about_title: 'Mission & Values',
    about_p: 'IBRAT Talim grew from a single classroom into a city-wide network. Our motto: <strong>quality education created by youth, for youth</strong>.',
    feat_1_title: 'Modern Methods', feat_1_p: 'Montessori, interactive learning and cutting-edge pedagogical technologies for fast and effective results.',
    feat_2_title: 'Expert Teachers', feat_2_p: 'Every teacher is an expert in their field, applying an individual approach to each student.',
    feat_3_title: 'All Ages Welcome', feat_3_p: 'From toddlers age 2 to adult learners — specialized programs for every age group.',
    adv_1_title: 'High Quality', adv_1_p: 'Curriculum and systems aligned with international standards.',
    adv_2_title: 'Innovation', adv_2_p: 'Interactive 3D platforms and hands-on practical projects.',
    adv_3_title: 'Guarantee', adv_3_p: 'The results you expect and a solid foundation of knowledge.',
    stat_students: 'Happy Students', stat_teachers: 'Expert Teachers', stat_programs: 'Programs', stat_years: 'Years Excellence',
    proc_label: 'How We Work', proc_title: '4 Simple', proc_title_green: 'Steps',
    proc_1: 'Consultation', proc_1_p: 'We assess your goals and recommend the best course for you.',
    proc_2: 'Placement Test', proc_2_p: 'A free diagnostic test to place you in the perfect group.',
    proc_3: 'Active Learning', proc_3_p: 'Interactive classes in modern classrooms with expert teachers.',
    proc_4: 'Achieve Results', proc_4_p: 'Pass exams, earn certificates (IELTS etc.) and apply your new skills!',
    courses_label: 'Education Paths', courses_title: 'Our', courses_title_green: 'Courses',
    tab_all: 'All', tab_lang: 'Languages', tab_kids: 'For Kids', tab_exam: 'Exam Prep',
    c_en_name: 'English Language', c_en_desc: 'Beginner to advanced. IELTS preparation, speaking clubs.',
    c_ru_name: 'Russian Language', c_ru_desc: 'Intensive course focused on live communication. Grammar & conversation.',
    c_ar_name: 'Arabic Language', c_ar_desc: 'Grammar, reading and modern conversational Arabic. Quranic Arabic included.',
    c_ko_name: 'Korean Language', c_ko_desc: 'From Hangul alphabet to conversational Korean for K-pop & business.',
    c_ma_name: 'Mental Arithmetic', c_ma_desc: 'Fast calculation with abacus, developing logical thinking. Ages 5–14.',
    c_mt_name: 'Montessori', c_mt_desc: 'Progressive methodology for nurturing independent learning. Ages 2–7.',
    c_ielts_name: 'IELTS / Exam Prep', c_ielts_desc: 'Intensive preparation targeting Band 7+. Mock tests included.',
    c_sr_name: 'Speed Reading', c_sr_desc: 'Increase reading speed 3–5x and improve information retention techniques.',
    learn_more: 'Learn More',
    branches_label: 'Our Branches', branches_title: 'Our', branches_title_green: 'Locations in Tashkent',
    branches_sub: 'Find a branch near you. We are constantly expanding.',
    br_1_name: 'Oltintepa Branch', br_1_addr: "Ko'ksaroy, Shifobaxsh suvlar St, 134", br_1_lm: 'Near "Oltintepa" Mosque',
    br_2_name: 'Yangi Darhon Branch', br_2_addr: "Navro'z Street, 20", br_2_lm: 'Yangi Darhon mahalla',
    br_3_name: 'Yangihayot Branch', br_3_addr: 'Yo\'ldosh-16, 12, Yangihayot District', br_3_lm: 'Near 37th Polyclinic',
    label_location: 'Location', label_landmark: 'Landmark', label_hours: 'Working Hours', label_phone: 'Phone',
    btn_map: 'View on Map',
    gallery_label: 'Photo Gallery', gallery_title: 'Inside', gallery_title_green: 'IBRAT Talim',
    g1: 'Modern Classrooms', g2: 'Interactive Learning', g3: 'Group Discussions',
    g4: 'Early Development', g5: 'Student Success', g6: 'Expert Guidance',
    reviews_label: 'Student Reviews', reviews_title: 'Success', reviews_title_green: 'Stories',
    t1_text: '"My daughter absolutely loves the Montessori classes! Her confidence has skyrocketed and the teachers are incredibly supportive."',
    t1_role: 'Parent of 5yo',
    t2_text: '"The intensive Russian course helped me land my dream job. The methodology here is highly practical and results-oriented."',
    t2_role: 'Adult Student',
    t3_text: '"Mental arithmetic has transformed the way my son thinks. He solves complex problems faster than I do now!"',
    t3_role: 'Parent of 9yo',
    contact_label: 'Contact', contact_title: 'Start Your Journey',
    contact_sub: 'Ready to enroll or have a question? Fill out the form — our team will get back to you shortly.',
    form_name: 'Full Name', form_name_ph: 'Your full name',
    form_phone: 'Phone Number', form_course: 'Course', form_course_ph: 'Select a course',
    form_msg: 'Message (optional)', form_msg_ph: 'Your question or comment...',
    btn_send: 'Send Request',
    footer_desc: 'Empowering minds through innovative education. Join our community and shape your future today.',
    footer_links: 'Quick Links', footer_branches: 'Our Branches',
    footer_contact: 'Contact Us', footer_info: 'For more information:',
    footer_copy: '© 2026 IBRAT Talim. All Rights Reserved.',
    cta_float: 'Enroll Now',
    course_back: 'Back', about_course: 'About the Course', what_learn: 'What You Will Learn',
    course_info: 'Course Information', label_duration: 'Duration',
    label_level: 'Level', label_cert: 'Certificate', val_yes: 'Yes',
    btn_enroll: 'Enroll Now', more_courses: 'More', more_courses_green: 'Courses',
    form_name_w: 'Your name', form_course_w: 'Select a course',
  },
};

const LangCtx = createContext({ lang: 'uz', setLang: () => {}, T: (k) => k });

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('uz');
  const T = (k) => t[lang]?.[k] ?? t.en?.[k] ?? k;
  return <LangCtx.Provider value={{ lang, setLang, T }}>{children}</LangCtx.Provider>;
};

export const useLang = () => useContext(LangCtx);
